Numpy = numeric + python 

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
ar = np.array(l)

In [4]:
ar  #it is one dimentional array beacuse of the single list []

array([1, 2, 3, 4, 5])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]]) #this is two dimentional arr

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray([1,2,3])  #this is also convert the the list in the array

array([1, 2, 3])

In [8]:
np.asanyarray([2,3,4]) #ans this method is also convert the list in the array

array([2, 3, 4])

In [9]:
b = np.matrix(l)  #here it will automatically convert the 2 d array

In [10]:
b

matrix([[1, 2, 3, 4, 5]])

In [11]:
a = np.array(l)

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
c = a

In [14]:
c

array([1, 2, 3, 4, 5])

In [15]:
c[0] = 100

In [16]:
c

array([100,   2,   3,   4,   5])

In [17]:
a

array([100,   2,   3,   4,   5])

In [18]:
d = np.copy(a)  #here we copy the array named a 

In [19]:
d

array([100,   2,   3,   4,   5])

In [20]:
d[1] = 200

In [21]:
d

array([100, 200,   3,   4,   5])

In [22]:
a

array([100,   2,   3,   4,   5])

In [23]:
np.fromfunction(lambda i,j : i==j ,(3,3)) #form function is used to generating and producing the array in any point of the time 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [25]:
iterable = (i*i for i in range(5))

In [26]:
np.fromiter(iterable , float )

array([ 0.,  1.,  4.,  9., 16.])

In [27]:
np.fromstring('234 264' , sep =' ')

array([234., 264.])

In [28]:
np.fromstring('4,5' , sep =' , ')

array([4., 5.])

NUMPY - DATATYPE

In [34]:
import numpy as np
l1 = [2,3,4,5,6]

In [35]:
ar = np.array(l1)

In [37]:
ar.ndim  #if you want to check the dimension of the array then you have to use ndim

1

In [39]:
ar2 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])

In [40]:
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
ar2.ndim  #ar2 is 2 dimension array

2

In [45]:
ar.size

5

In [46]:
ar2.size

10

In [47]:
ar.shape

(5,)

In [48]:
ar2.shape

(2, 5)

In [49]:
ar.dtype

dtype('int32')

In [51]:
ar22 = np.array([(1.2,45,45) , (2,48,33)])

In [52]:
ar22

array([[ 1.2, 45. , 45. ],
       [ 2. , 48. , 33. ]])

In [54]:
ar22.dtype

dtype('float64')

In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [59]:
np.arange(2.3,5.6,.3) #here the data is jumping by 3 points 

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [60]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [62]:
np.linspace(1,5,10) #it is basically used to generate the number between the range 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [65]:
np.zeros(5) #here all the data becomes 0

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
zr = np.zeros((3,4,2)) #if we want to represent the array in 3d form then have to do this

In [71]:
zr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [69]:
zr.ndim

3

In [73]:
np.ones(4)

array([1., 1., 1., 1.])

In [77]:
on = np.ones((3,2,2))

In [78]:
on

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [79]:
on + 5

array([[[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]]])

In [80]:
on * 6

array([[[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]]])

In [82]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
np.eye(4) #eye is identity matrix here the data show in the digonally 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [86]:
np.logspace(2,5,10 , base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [92]:
#Random function is used to produce the random number 
arr = np.random.randn(3,4) #Want to produce the random data then use random function
#the randn function is used to generate the data which has mean = 0 & standard deviation = 1

In [93]:
import pandas as pd

In [94]:
pd.DataFrame(arr) #here we create the data frame using the numpy array


0         1         2         3
0 -1.059912  1.996295 -0.540389 -0.032656
1  0.447253 -1.217813 -1.207470 -2.269472
2 -0.121771  0.101327 -0.578704 -0.801307

In [95]:
np.random.rand(3,4)

array([[0.2047513 , 0.33912407, 0.85716183, 0.37905386],
       [0.55669964, 0.89023154, 0.65235068, 0.33154084],
       [0.77874691, 0.2706345 , 0.21496877, 0.05736887]])

In [96]:
np.random.randint(1,110,(3,4))

array([[ 86,  77,  21,   7],
       [ 76,  68,  27, 100],
       [ 70,  92, 105,  75]])

In [98]:
pd.DataFrame(np.random.randint(1,110 ,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     51  103   55   84   57   28   18    2   18  108  ...   80   61   14   
1     68   48   68   20    1   34   85  100   54  107  ...    9   94   92   
2     97  107   67   53   19   46   80   41   26   48  ...  102   47   23   
3     22   57    5   85    3   32   18   47   57   91  ...   42   42   76   
4     21  105   78  107   62   56   67    4   44   92  ...  109   63  101   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   29   60   57   59   31   27  100   95   90   55  ...   95   35   77   
296   98   37   14   74   59   84   84   82    5   63  ...   74   58   53   
297   40   23   84   73   72   61    6   27   80   99  ...   36    8   50   
298   68   63   81   65   91   74   40   73   70   62  ...   79   26   80   
299   49   80   68   51   16   90    8   55    9   47  ...   27   28    1   

     393  394  395  396  397  398  399  
0     86    2   29  102    4   32   14  
1     40   63   15   50   62   74   39  
2     50   37   31   73   50   25   73  
3      6   75   53  108   44   81   37  
4     48   93  106   40   81    1   55  
..   ...  ...  ...  ...  ...  ...  ...  
295   97   68   76   78  101   43   23  
296   76   21   57  104   43   18  108  
297   15  106   32    6   75  107   96  
298   89   75    7   48   64   87   92  
299   75   81   14   20   96   78   35  

[300 rows x 400 columns]

In [99]:
#Convert this to csv file 
pd.DataFrame(np.random.randint(1,110 ,(300,400))).to_csv('test.csv')

In [112]:
arr = np.random.rand(3,4)

In [113]:
arr

array([[0.11293431, 0.88386536, 0.70013236, 0.86300863],
       [0.21247238, 0.72950521, 0.58517399, 0.56325473],
       [0.19801741, 0.59336157, 0.04023291, 0.31959086]])

In [114]:
arr.reshape(6,2)

array([[0.11293431, 0.88386536],
       [0.70013236, 0.86300863],
       [0.21247238, 0.72950521],
       [0.58517399, 0.56325473],
       [0.19801741, 0.59336157],
       [0.04023291, 0.31959086]])

In [116]:
arr.reshape(6,-1)

array([[0.11293431, 0.88386536],
       [0.70013236, 0.86300863],
       [0.21247238, 0.72950521],
       [0.58517399, 0.56325473],
       [0.19801741, 0.59336157],
       [0.04023291, 0.31959086]])

In [117]:
arr1 = arr.reshape(6,-1)

In [118]:
arr1

array([[0.11293431, 0.88386536],
       [0.70013236, 0.86300863],
       [0.21247238, 0.72950521],
       [0.58517399, 0.56325473],
       [0.19801741, 0.59336157],
       [0.04023291, 0.31959086]])

In [121]:
arr1[1][1]

0.86300862719405

In [122]:
arr1[2:5 , 1]

array([0.72950521, 0.56325473, 0.59336157])

In [133]:
arr = np.random.randint(1,100 , (5,5))

In [134]:
arr

array([[16, 45,  3, 78, 59],
       [31, 55, 92, 72,  1],
       [14, 66, 15, 65, 99],
       [54, 84, 41, 56,  8],
       [87,  1, 81, 46,  7]])

In [135]:
arr>50

array([[False, False, False,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True, False, False]])

In [136]:
arr[arr>50] #extracting the data which is greater then 50

array([78, 59, 55, 92, 72, 66, 65, 99, 54, 84, 56, 87, 81])

In [137]:
 arr

array([[16, 45,  3, 78, 59],
       [31, 55, 92, 72,  1],
       [14, 66, 15, 65, 99],
       [54, 84, 41, 56,  8],
       [87,  1, 81, 46,  7]])

In [140]:
arr[2:4 , [1,2]]

array([[66, 15],
       [84, 41]])

In [144]:
arr1 = np.random.randint(1 ,10 ,(5,5))

In [145]:
arr1

array([[2, 2, 8, 5, 8],
       [6, 6, 8, 1, 9],
       [4, 3, 3, 4, 2],
       [9, 2, 6, 2, 8],
       [6, 7, 7, 3, 4]])

In [147]:
arr1 * arr1

array([[ 4,  4, 64, 25, 64],
       [36, 36, 64,  1, 81],
       [16,  9,  9, 16,  4],
       [81,  4, 36,  4, 64],
       [36, 49, 49,  9, 16]])

In [148]:
arr1/0

C:\Users\77piy\AppData\Local\Temp\ipykernel_9636\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [149]:
arr + 100

array([[116, 145, 103, 178, 159],
       [131, 155, 192, 172, 101],
       [114, 166, 115, 165, 199],
       [154, 184, 141, 156, 108],
       [187, 101, 181, 146, 107]])

In [150]:
arr1 ** 2

array([[ 4,  4, 64, 25, 64],
       [36, 36, 64,  1, 81],
       [16,  9,  9, 16,  4],
       [81,  4, 36,  4, 64],
       [36, 49, 49,  9, 16]])

In [154]:
#Broadcasting = basically the add the array the array 
ar = np.zeros((4,4))

In [158]:
row = np.array([1,2,3,4])

In [159]:
ar + row  

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [160]:
row.ndim

1

In [161]:
row.T

array([1, 2, 3, 4])

In [162]:
col = np.array([[1,2,3,4]])

In [163]:
col

array([[1, 2, 3, 4]])

In [165]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])